/* =========================================================
   Yeguada Tres Tréboles — LOS DATOS DE LOS CABALLOS
   Este es el único archivo que hay que tocar para añadir,
   quitar o corregir un caballo. De aquí sale toda la web.

   Es un .js y no un .json porque así la web funciona al
   abrir los archivos directamente, sin necesidad de servidor.
   El contenido se edita igual: cada caballo entre llaves.
   ========================================================= */

const CABALLOS = [
  {
    "slug": "provinciano-sm-iii",
    "nombre": "Provinciano SM III",
    "grupo": "semental",
    "sexo": "M",
    "nacimiento": "2014-05-17",
    "capa": "Negra",
    "padre": "Nobiliario SM",
    "padreSlug": null,
    "madre": "Provinciana II",
    "madreSlug": null,
    "criador": "Salvador Miras Gómez",
    "lugarNacimiento": null,
    "descendencia": [
      "soberano-tres-treboles",
      "nervion-tres-treboles",
      "nervion-ii-tres-t",
      "soberano-ii-tres-t"
    ],
    "cubriciones": true,
    "enVenta": false,
    "vendido": false,
    "destacado": true,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg",
      "02.jpg",
      "03.jpg",
      "04.jpg"
    ],
    "video": null,
    "credito": "Salvador Giménez Fotografía",
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 12,
    "videos": [],
    "igg": "108,05",
    "iggFiab": "alta",
    "creditoPortada": "Salvador Giménez Fotografía",
    "hijosReg": [
      {
        "nombre": "Lesa Navero",
        "anio": 2017,
        "capa": "Baya",
        "otro": "Cantiña SM",
        "slug": null
      },
      {
        "nombre": "Califa CLX",
        "anio": 2018,
        "capa": "Negra",
        "otro": "Famosa SM",
        "slug": null
      },
      {
        "nombre": "Eclipse Navero",
        "anio": 2020,
        "capa": "Castaña",
        "otro": "Triana LXII",
        "slug": null
      },
      {
        "nombre": "Farrukito IV",
        "anio": 2022,
        "capa": "Negra",
        "otro": "Malaguita III",
        "slug": null
      },
      {
        "nombre": "Idílico LC",
        "anio": 2023,
        "capa": "Negra",
        "otro": "Alba Madroñal",
        "slug": null
      },
      {
        "nombre": "Provinciana VI",
        "anio": 2023,
        "capa": "Negra",
        "otro": "Valvuena",
        "slug": null
      },
      {
        "nombre": "Nervión Tres Tréboles",
        "anio": 2024,
        "capa": "Negra",
        "otro": "Nerva Navero",
        "slug": "nervion-tres-treboles"
      },
      {
        "nombre": "Soberano Tres Tréboles",
        "anio": 2024,
        "capa": "Castaña",
        "otro": "NR Malusa",
        "slug": "soberano-tres-treboles"
      },
      {
        "nombre": "Bejarano Font",
        "anio": 2025,
        "capa": "Alazana",
        "otro": "Rifirrafe Frague",
        "slug": null
      },
      {
        "nombre": "Jammer LC",
        "anio": 2025,
        "capa": "Negra",
        "otro": "Belia CE",
        "slug": null
      },
      {
        "nombre": "Nervión II Tres T",
        "anio": 2025,
        "capa": "Negra",
        "otro": "Nerva Navero",
        "slug": "nervion-ii-tres-t"
      },
      {
        "nombre": "Soberano II Tres T",
        "anio": 2026,
        "capa": "Negra",
        "otro": "NR Malusa",
        "slug": "soberano-ii-tres-t"
      }
    ]
  },
  {
    "slug": "tatami-jmg",
    "nombre": "Tatami JMG",
    "grupo": "semental",
    "sexo": "M",
    "nacimiento": "2023-06-10",
    "capa": "Castaña",
    "padre": "Señor de Centurión",
    "padreSlug": null,
    "madre": "Divertida ADT",
    "madreSlug": null,
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": true,
    "enVenta": false,
    "vendido": false,
    "destacado": true,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [
      {
        "archivo": "videotatami01.mp4",
        "poster": "videotatami01-poster.jpg"
      }
    ],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "japonesa-xiv",
    "nombre": "Japonesa XIV",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2004-03-24",
    "capa": "Castaña",
    "padre": "Educado X",
    "padreSlug": null,
    "madre": "Seductora XI",
    "madreSlug": null,
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 9,
    "videos": [],
    "igg": "104,22",
    "iggFiab": null,
    "creditoPortada": null,
    "hijosReg": [
      {
        "nombre": "Japonés III",
        "anio": 2009,
        "capa": "Castaña",
        "otro": "Zoilo IX",
        "slug": null
      },
      {
        "nombre": "Japonés MFE",
        "anio": 2012,
        "capa": "Castaña",
        "otro": "Discreto XIII",
        "slug": null
      },
      {
        "nombre": "Japonés MFE II",
        "anio": 2015,
        "capa": "Castaña",
        "otro": "Hebreo XIX",
        "slug": null
      },
      {
        "nombre": "Japonés MFE III",
        "anio": 2017,
        "capa": "Castaña",
        "otro": "Hebreo Al Andalus",
        "slug": null
      },
      {
        "nombre": "Japonés MFE IV",
        "anio": 2019,
        "capa": "Castaña",
        "otro": "Talismán MFE",
        "slug": null
      },
      {
        "nombre": "Japonés MFE V",
        "anio": 2020,
        "capa": "Castaña",
        "otro": "Hebreo Al Andalus",
        "slug": null
      },
      {
        "nombre": "Japonés MFE VI",
        "anio": 2021,
        "capa": "Castaña",
        "otro": "Hebreo Al Andalus",
        "slug": null
      },
      {
        "nombre": "Japonés MFE VII",
        "anio": 2023,
        "capa": "Castaña",
        "otro": "Jaquetón MFE III",
        "slug": null
      },
      {
        "nombre": "Japonés MFE VIII",
        "anio": 2025,
        "capa": "Castaña",
        "otro": "Jaquetón MFE III",
        "slug": null
      }
    ]
  },
  {
    "slug": "faraona-mfe",
    "nombre": "Faraona MFE",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2021-03-28",
    "capa": "Castaña",
    "padre": "Romero MFE",
    "padreSlug": null,
    "madre": "Quimera MFE",
    "madreSlug": null,
    "criador": "MFE",
    "lugarNacimiento": null,
    "descendencia": [
      "saeta-tres-t"
    ],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg",
      "02.jpg",
      "03.jpg",
      "04.jpg",
      "06.jpg"
    ],
    "video": null,
    "credito": "Picazo audiovisual",
    "palmares": [
      {
        "anio": 2026,
        "puesto": 2,
        "concurso": "FIECVAL",
        "seccion": "S9",
        "puntos": "75,325",
        "titulo": "Subcampeona de Europa",
        "nota": null
      },
      {
        "anio": 2026,
        "puesto": 5,
        "concurso": "Jerez — Cartuja",
        "seccion": "S9",
        "puntos": "71,225",
        "titulo": null,
        "nota": null
      },
      {
        "anio": 2025,
        "puesto": 1,
        "concurso": "SICAB — XI Campeonato del Mundo del Caballo PRE",
        "seccion": "S14",
        "puntos": "71,100",
        "titulo": "Campeona del mundo en cobra",
        "nota": "En la cobra de cinco de la ganadería María Fernanda de la Escalera"
      },
      {
        "anio": 2025,
        "puesto": 3,
        "concurso": "Mazarrón",
        "seccion": "S7",
        "puntos": "71,275",
        "titulo": null,
        "nota": null
      },
      {
        "anio": 2024,
        "puesto": 1,
        "concurso": "Equus Socuéllamos",
        "seccion": "S5",
        "puntos": "82,550",
        "titulo": "Primer premio",
        "nota": "Mejor movimiento"
      },
      {
        "anio": 2024,
        "puesto": 1,
        "concurso": "Equus Villamanta",
        "seccion": "S5",
        "puntos": "77,375",
        "titulo": "Primer premio",
        "nota": null
      },
      {
        "anio": 2024,
        "puesto": 4,
        "concurso": "Torrejoncillo",
        "seccion": "S5",
        "puntos": "75,400",
        "titulo": null,
        "nota": null
      },
      {
        "anio": 2024,
        "puesto": 8,
        "concurso": "Bormujos PRE",
        "seccion": "S5",
        "puntos": "71,275",
        "titulo": null,
        "nota": null
      },
      {
        "anio": 2024,
        "puesto": 19,
        "concurso": "SICAB — X Campeonato del Mundo del Caballo PRE",
        "seccion": "S5",
        "puntos": "73,567",
        "titulo": null,
        "nota": null
      }
    ],
    "arbol": "arbol.jpg",
    "hijosLG": 1,
    "videos": [
      {
        "archivo": "video-faraona.mp4",
        "poster": "video-faraona-poster.jpg"
      }
    ],
    "igg": "110,48",
    "iggFiab": "baja",
    "creditoPortada": null
  },
  {
    "slug": "hacendada-mfe",
    "nombre": "Hacendada MFE",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2023-03-19",
    "capa": "Castaña",
    "padre": "Dátil MFE",
    "padreSlug": null,
    "madre": "Barquera MFE",
    "madreSlug": null,
    "criador": "MFE",
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg",
      "02.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "pompita-erre",
    "nombre": "Pompita Erre",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2011-04-02",
    "capa": "Castaña",
    "padre": "War-Horse-JEM",
    "padreSlug": null,
    "madre": "Cariñosa LIV",
    "madreSlug": null,
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "utrera-hm",
    "nombre": "Utrera HM",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2012-04-28",
    "capa": "Castaña",
    "padre": "Neptuno XI",
    "padreSlug": null,
    "madre": "Leyenda HM",
    "madreSlug": null,
    "criador": "Bartolomé Herruzo Moreno",
    "lugarNacimiento": null,
    "descendencia": [
      "canastera-tres-t"
    ],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 5,
    "videos": [],
    "igg": "99,71",
    "iggFiab": "baja",
    "creditoPortada": null,
    "hijosReg": [
      {
        "nombre": "Alaska XXII",
        "anio": 2019,
        "capa": "Castaña",
        "otro": "Boletus SB",
        "slug": null
      },
      {
        "nombre": "Cigarrera K",
        "anio": 2021,
        "capa": "Castaña",
        "otro": "Sandocán AC",
        "slug": null
      },
      {
        "nombre": "Utrera K",
        "anio": 2022,
        "capa": "Alazana",
        "otro": "Epon de Vale",
        "slug": null
      },
      {
        "nombre": "Morisco Andalusí",
        "anio": 2025,
        "capa": "Castaña",
        "otro": "Príncipe Lorenzana",
        "slug": null
      },
      {
        "nombre": "Canastera Tres T",
        "anio": 2026,
        "capa": "Torda",
        "otro": "Pericón de Torres",
        "slug": "canastera-tres-t"
      }
    ]
  },
  {
    "slug": "nr-malusa",
    "nombre": "NR Malusa",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2014-02-15",
    "capa": "Castaña",
    "padre": "Espigón III",
    "padreSlug": null,
    "madre": "Farruca CXXXVIII",
    "madreSlug": null,
    "criador": "Yeguada El Romerito",
    "lugarNacimiento": null,
    "descendencia": [
      "soberano-tres-treboles",
      "soberano-ii-tres-t"
    ],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg",
      "02.jpg",
      "03.jpg"
    ],
    "video": null,
    "credito": "Salvador Giménez Fotografía",
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 4,
    "videos": [
      {
        "archivo": "videomalusa.mp4",
        "poster": "videomalusa-poster.jpg"
      },
      {
        "archivo": "videomalusa02.mp4",
        "poster": "videomalusa02-poster.jpg"
      }
    ],
    "igg": "106,86",
    "iggFiab": "alta",
    "creditoPortada": "Salvador Giménez Fotografía",
    "hijosReg": [
      {
        "nombre": "Umbrete de Cuenca",
        "anio": 2019,
        "capa": "Castaña",
        "otro": "Amazonas AR",
        "slug": null
      },
      {
        "nombre": "Crimea Navero",
        "anio": 2023,
        "capa": "Castaña",
        "otro": "Faneguero La Bellota",
        "slug": null
      },
      {
        "nombre": "Soberano Tres Tréboles",
        "anio": 2024,
        "capa": "Castaña",
        "otro": "Provinciano SM III",
        "slug": "soberano-tres-treboles"
      },
      {
        "nombre": "Soberano II Tres T",
        "anio": 2026,
        "capa": "Negra",
        "otro": "Provinciano SM III",
        "slug": "soberano-ii-tres-t"
      }
    ]
  },
  {
    "slug": "nerva-navero",
    "nombre": "Nerva Navero",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2020-06-17",
    "capa": "Negra",
    "padre": "Oe Oe Oe Oe Frague",
    "padreSlug": null,
    "madre": "Gamarra III",
    "madreSlug": null,
    "criador": "Francisco José Guerrero López",
    "lugarNacimiento": null,
    "descendencia": [
      "nervion-tres-treboles",
      "nervion-ii-tres-t"
    ],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": true,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 3,
    "videos": [],
    "igg": "105,37",
    "iggFiab": "baja",
    "creditoPortada": null,
    "hijosReg": [
      {
        "nombre": "Cautiva Navero",
        "anio": 2023,
        "capa": "Castaña",
        "otro": "Norte A",
        "slug": null
      },
      {
        "nombre": "Nervión Tres Tréboles",
        "anio": 2024,
        "capa": "Negra",
        "otro": "Provinciano SM III",
        "slug": "nervion-tres-treboles"
      },
      {
        "nombre": "Nervión II Tres T",
        "anio": 2025,
        "capa": "Negra",
        "otro": "Provinciano SM III",
        "slug": "nervion-ii-tres-t"
      }
    ]
  },
  {
    "slug": "betica-vr",
    "nombre": "Bética VR",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2021-05-04",
    "capa": "Castaña",
    "padre": "Bony Torreluna",
    "padreSlug": null,
    "madre": "Granadilla RAB",
    "madreSlug": null,
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "bonachona-de-vinuesa",
    "nombre": "Bonachona de Vinuesa",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2022-03-11",
    "capa": "Castaña",
    "padre": "Impacto MB",
    "padreSlug": null,
    "madre": "Mañosa Puente Romano",
    "madreSlug": null,
    "criador": null,
    "lugarNacimiento": "Finca La Loma, Córdoba",
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "nervion-tres-treboles",
    "nombre": "Nervión Tres Tréboles",
    "grupo": "nacido-aqui",
    "sexo": "M",
    "nacimiento": "2024-11-25",
    "capa": "Negra",
    "padre": "Provinciano SM III",
    "padreSlug": "provinciano-sm-iii",
    "madre": "Nerva Navero",
    "madreSlug": "nerva-navero",
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": true,
    "destacado": false,
    "hito": null,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null,
    "nota": "Nacido en la yeguada. Hoy ya no está aquí; conserva el nombre con el que se inscribió."
  },
  {
    "slug": "nervion-ii-tres-t",
    "nombre": "Nervión II Tres T",
    "grupo": "nacido-aqui",
    "sexo": "M",
    "nacimiento": "2025-10-23",
    "capa": "Negra",
    "padre": "Provinciano SM III",
    "padreSlug": "provinciano-sm-iii",
    "madre": "Nerva Navero",
    "madreSlug": "nerva-navero",
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "soberano-ii-tres-t",
    "nombre": "Soberano II Tres T",
    "grupo": "nacido-aqui",
    "sexo": "M",
    "nacimiento": "2026-01-31",
    "capa": "Negra",
    "padre": "Provinciano SM III",
    "padreSlug": "provinciano-sm-iii",
    "madre": "NR Malusa",
    "madreSlug": "nr-malusa",
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "canastera-tres-t",
    "nombre": "Canastera Tres T",
    "grupo": "nacido-aqui",
    "sexo": "H",
    "nacimiento": "2026-03-24",
    "capa": "Torda",
    "padre": "Pericón de Torres",
    "padreSlug": null,
    "madre": "Utrera HM",
    "madreSlug": "utrera-hm",
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": true,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "saeta-tres-t",
    "nombre": "Saeta Tres T",
    "grupo": "nacido-aqui",
    "sexo": "H",
    "nacimiento": "2026-04-02",
    "capa": "Castaña",
    "padre": "Dátil MFE",
    "padreSlug": null,
    "madre": "Faraona MFE",
    "madreSlug": "faraona-mfe",
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": true,
    "hito": "La más joven de la yeguada",
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "amaranto-xxviii",
    "nombre": "Amaranto XXVIII",
    "grupo": "venta",
    "sexo": "M",
    "nacimiento": "2023-06-07",
    "capa": "Bayo",
    "padre": "Norte A",
    "padreSlug": null,
    "madre": "Malaguita III",
    "madreSlug": null,
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": true,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null
  },
  {
    "slug": "castorena-ix",
    "nombre": "Castoreña IX",
    "grupo": "venta",
    "sexo": "H",
    "nacimiento": "2008-04-10",
    "capa": "Torda",
    "padre": "Castor II",
    "padreSlug": null,
    "madre": "Soñadora XVI",
    "madreSlug": null,
    "criador": "Antonio Cañete Galacho",
    "lugarNacimiento": "Finca Calamorro, Málaga",
    "descendencia": [],
    "cubriciones": false,
    "enVenta": true,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [
      "portada.jpg",
      "01.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": "95,73",
    "iggFiab": "baja",
    "creditoPortada": null
  },
  {
    "slug": "soberano-tres-treboles",
    "nombre": "Soberano Tres Tréboles",
    "grupo": "nacido-aqui",
    "sexo": "M",
    "nacimiento": "2024-11-19",
    "capa": "Castaña",
    "padre": "Provinciano SM III",
    "padreSlug": "provinciano-sm-iii",
    "madre": "NR Malusa",
    "madreSlug": "nr-malusa",
    "criador": null,
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": true,
    "destacado": false,
    "hito": null,
    "texto": "",
    "fotos": [
      "portada.jpg"
    ],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 0,
    "videos": [],
    "igg": null,
    "iggFiab": null,
    "creditoPortada": null,
    "nota": "Nacido en la yeguada. Hoy ya no está aquí; conserva el nombre con el que se inscribió."
  },
  {
    "slug": "distinguida-xci",
    "nombre": "Distinguida XCI",
    "grupo": "yegua",
    "sexo": "H",
    "nacimiento": "2012-05-18",
    "capa": "Torda",
    "padre": "Nobiliario SM",
    "padreSlug": null,
    "madre": "Usía XIII",
    "madreSlug": null,
    "criador": "Salvador Miras Gómez",
    "lugarNacimiento": null,
    "descendencia": [],
    "cubriciones": false,
    "enVenta": false,
    "vendido": false,
    "destacado": false,
    "texto": "",
    "fotos": [],
    "video": null,
    "credito": null,
    "palmares": [],
    "arbol": "arbol.jpg",
    "hijosLG": 5,
    "videos": [],
    "igg": "106,66",
    "iggFiab": "alta",
    "creditoPortada": null,
    "hito": null,
    "nota": null,
    "hijosReg": [
      {
        "nombre": "Tormenta YT",
        "anio": 2017,
        "capa": "Torda",
        "otro": "Salomón SM III",
        "slug": null
      },
      {
        "nombre": "Distinguido YT",
        "anio": 2019,
        "capa": "Castaña",
        "otro": "Espléndido RAM",
        "slug": null
      },
      {
        "nombre": "Distinguido K",
        "anio": 2022,
        "capa": "Alazana",
        "otro": "Epon de Vale",
        "slug": null
      },
      {
        "nombre": "Olimpo K",
        "anio": 2023,
        "capa": "Castaña",
        "otro": "Príncipe Lorenzana",
        "slug": null
      },
      {
        "nombre": "Nobiliaria K",
        "anio": 2024,
        "capa": "Castaña",
        "otro": "Príncipe Lorenzana",
        "slug": null
      }
    ]
  }
];
